@host=http://localhost:3000

###
# Get List of To Do Items
GET {{host}}/todos HTTP/1.1

###
# Create new To Do Item
POST {{host}}/todos HTTP/1.1
content-type: application/json

{
    "task": "help Anarane",
    "completed": false
}

###
# Update To Do Item
@task_id=1

PUT {{host}}/todos/{{task_id}} HTTP/1.1
content-type: application/json

{
    "task": "help Jane",
    "completed": true
}

###
# Delete To Do Item
DELETE {{host}}/todos/{{task_id}} HTTP/1.1

###
# Clear Completed To Do Items
POST {{host}}/todos/clear-completed HTTP/1.1
