GET http://localhost:3000/todos HTTP/1.1

###

POST http://localhost:3000/todos HTTP/1.1
content-type: application/json

{
    "task": "help michale",
    "completed": false
}

###

@task_id=3

DELETE http://localhost:3000/todos/{{task_id}} HTTP/1.1

###
